### ISSUE TITLE
 Options and their values can not be created directly, dynamically

### ISSUE THREAD

**Issue by mironsoft75** [mygento/module-import-export#2]
Hi

Options and their values can not be created directly, dynamically. These must always be created before? Is that correct?

Vladimir

**Comment by Mavlyan** [comment]
Hello, Vladimir!

Attributes should be created before.
But options and their values should be created automatically, during the import process (method _Mygento\ImportExport\Model\Product\Attribute::createAttributeOption();_ does it)

See Model/Product/Attribute.php:68 for details.
